/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    actualites: Actualite;
    evenements: Evenement;
    equipe: Equipe;
    temoignages: Temoignage;
    partenaires: Partenaire;
    documents: Document;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    evenements: EvenementsSelect<false> | EvenementsSelect<true>;
    equipe: EquipeSelect<false> | EquipeSelect<true>;
    temoignages: TemoignagesSelect<false> | TemoignagesSelect<true>;
    partenaires: PartenairesSelect<false> | PartenairesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Identifiant URL-safe, ex: 'accueil', 'qui-sommes-nous'. Sert à matcher la route Astro.
   */
  slug: string;
  /**
   * ~150 caractères, affiché dans Google.
   */
  description?: string | null;
  /**
   * Si coché, demande aux moteurs de ne pas indexer.
   */
  noindex?: boolean | null;
  hero?: {
    /**
     * Décocher si la page commence directement par les sections.
     */
    enabled?: boolean | null;
    /**
     * Astuce : *italique* sur un mot pour l'accent serif.
     */
    titre?: string | null;
    sousTitre?: string | null;
    accroche?: string | null;
    variant?: ('beige' | 'orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
    cta_primaire?: {
      label?: string | null;
      href?: string | null;
      externe?: boolean | null;
    };
    cta_secondaire?: {
      label?: string | null;
      href?: string | null;
      externe?: boolean | null;
    };
  };
  /**
   * Compose la page en empilant des sections. Chaque section est un type de bloc différent.
   */
  sections?:
    | (
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            /**
             * Markdown : ## titres, **gras**, *italique*, [lien](url), - listes…
             */
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            ton: 'info' | 'important' | 'astuce' | 'note';
            titre?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            /**
             * Première ligne, en italique.
             */
            ouverture?: string | null;
            /**
             * Plusieurs paragraphes (séparés par lignes vides). *italique* pour l'accent.
             */
            corps: string;
            signature?: string | null;
            variant: 'orange' | 'violet';
            id?: string | null;
            blockName?: string | null;
            blockType: 'lettre';
          }
        | {
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            citation: string;
            auteur: string;
            role?: string | null;
            variant: 'beige' | 'violet' | 'paper';
            /**
             * Marque la citation comme fictive (badge « À valider » côté site).
             */
            fictif?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation';
          }
        | {
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            citation: string;
            auteur?: string | null;
            role?: string | null;
            variant: 'orange' | 'violet' | 'beige' | 'paper';
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation-large';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            /**
             * Court : 90 %, 1/3, ×4…
             */
            chiffre: string;
            /**
             * Une à deux phrases. *italique* pour mettre en valeur un chiffre secondaire.
             */
            texte: string;
            source?: string | null;
            eyebrow?: string | null;
            variant: 'orange' | 'violet';
            id?: string | null;
            blockName?: string | null;
            blockType: 'stat-majeste';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            /**
             * Ex: 90 %, 1/3, 7 M+
             */
            chiffre: string;
            texte: string;
            source?: string | null;
            alignement: 'gauche' | 'droite';
            couleur?: ('orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'chiffre-detail';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            colonnes: '2' | '3' | '4';
            cartes: {
              titre: string;
              description: string;
              href?: string | null;
              cta?: string | null;
              couleur?: ('orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cartes';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            valeurs: {
              nom: string;
              description: string;
              couleur?: ('orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'valeurs';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            colonnes: '2' | '3';
            formats: {
              titre: string;
              description?: string | null;
              points?:
                | {
                    point: string;
                    id?: string | null;
                  }[]
                | null;
              couleur?: ('orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
              cta?: {
                label?: string | null;
                href?: string | null;
                externe?: boolean | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'formats';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            couleur?: ('orange' | 'violet' | 'magenta' | 'vert' | 'bleu') | null;
            etapes: {
              titre: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'etapes';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            questions: {
              question: string;
              reponse: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            intro?: string | null;
            stats: {
              valeur: string;
              legende: string;
              source?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            /**
             * Inverse l'ordre (image à gauche, texte à droite).
             */
            inverse?: boolean | null;
            texte: string;
            picto_couleur: 'orange' | 'violet' | 'magenta' | 'vert' | 'bleu' | 'beige';
            image?: (number | null) | Media;
            /**
             * Texte alternatif (override de l'alt de la media).
             */
            image_alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'deux-colonnes';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            texte: string;
            image?: (number | null) | Media;
            image_alt?: string | null;
            image_legende?: string | null;
            image_credit?: string | null;
            position: 'droite' | 'gauche';
            ratio: '50-50' | '2-tiers-texte' | '2-tiers-image';
            id?: string | null;
            blockName?: string | null;
            blockType: 'texte-photo';
          }
        | {
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            image?: (number | null) | Media;
            alt?: string | null;
            legende?: string | null;
            credit?: string | null;
            taille: 'petite' | 'moyenne' | 'grande';
            id?: string | null;
            blockName?: string | null;
            blockType: 'figure';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            colonnes: '2' | '3' | '4';
            /**
             * Active l'ouverture en plein écran au clic.
             */
            lightbox?: boolean | null;
            images: {
              image?: (number | null) | Media;
              alt?: string | null;
              legende?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'galerie';
          }
        | {
            image?: (number | null) | Media;
            alt?: string | null;
            titre: string;
            sousTitre?: string | null;
            hauteur: 'petite' | 'moyenne' | 'grande';
            position_texte: 'gauche' | 'centre' | 'droite';
            position_verticale: 'haut' | 'milieu' | 'bas';
            /**
             * Voile sombre pour la lisibilité du texte.
             */
            scrim?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bandeau-image';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            colonnes: '2' | '3' | '4';
            forme: 'rond' | 'carre';
            personnes: {
              nom: string;
              role?: string | null;
              photo?: (number | null) | Media;
              photo_alt?: string | null;
              bio?: string | null;
              lien?: string | null;
              lien_label?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'portraits';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            alignement: 'vertical' | 'alterne';
            etapes: {
              /**
               * Ex: 2024, Mars 2025, 15 juin…
               */
              date: string;
              titre: string;
              texte?: string | null;
              image?: (number | null) | Media;
              image_alt?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            contexte?: ('participante' | 'partenaire' | 'professionnelle') | null;
            limite: number;
            /**
             * Laisse vide pour tirer automatiquement. Sinon liste les slugs.
             */
            ids?:
              | {
                  slug: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'temoignages';
          }
        | {
            titre?: string | null;
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            intro?: string | null;
            forme: 'rond' | 'carre';
            colonnes: '2' | '3' | '4';
            /**
             * Laisse vide pour afficher tous. Sinon liste les slugs (ex: audrey-relandeau).
             */
            ids?:
              | {
                  slug: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipe';
          }
        | {
            fond?: ('paper' | 'beige' | 'violet' | 'orange' | 'magenta' | 'vert' | 'bleu') | null;
            titre: string;
            corps?: string | null;
            cta_primaire?: {
              label?: string | null;
              href?: string | null;
              externe?: boolean | null;
            };
            cta_secondaire?: {
              label?: string | null;
              href?: string | null;
              externe?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: number;
  title: string;
  /**
   * Identifiant URL, ex: 'lancement-association'.
   */
  slug: string;
  description?: string | null;
  date: string;
  auteur?: string | null;
  cover?: (number | null) | Media;
  /**
   * Alt override (sinon on prend l'alt de la media).
   */
  cover_alt?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ## titres, **gras**, *italique*, [liens](url), - listes…
   */
  body: string;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements".
 */
export interface Evenement {
  id: number;
  title: string;
  slug: string;
  date_debut: string;
  date_fin?: string | null;
  lieu: string;
  adresse?: string | null;
  cover?: (number | null) | Media;
  public: 'tout public' | 'professionnels' | 'femmes concernées' | 'adhérents';
  gratuit?: boolean | null;
  inscription_url?: string | null;
  body?: string | null;
  /**
   * Événement de démonstration — badge « À valider ».
   */
  fictif?: boolean | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe".
 */
export interface Equipe {
  id: number;
  /**
   * URL-safe, ex: 'audrey-relandeau'.
   */
  slug: string;
  nom: string;
  role: string;
  photo?: (number | null) | Media;
  bio_courte?: string | null;
  linkedin?: string | null;
  /**
   * Plus petit = plus haut dans la liste.
   */
  ordre?: number | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages".
 */
export interface Temoignage {
  id: number;
  slug: string;
  auteur: string;
  role?: string | null;
  contexte: 'participante' | 'partenaire' | 'professionnelle';
  photo?: (number | null) | Media;
  citation: string;
  ordre?: number | null;
  /**
   * Si coché, candidat à la mise en avant home (un seul à la fois).
   */
  a_la_une?: boolean | null;
  /**
   * Marque comme fictif (badge « À valider »).
   */
  fictif?: boolean | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires".
 */
export interface Partenaire {
  id: number;
  slug: string;
  nom: string;
  type: 'financeur public' | 'financeur privé' | 'partenaire associatif' | 'réseau';
  logo?: (number | null) | Media;
  url?: string | null;
  description_courte?: string | null;
  ordre?: number | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  slug: string;
  titre: string;
  categorie: 'projet associatif' | "rapport d'activité" | 'ressource' | 'communication' | 'présentation';
  /**
   * PDF ou autre fichier téléchargeable.
   */
  fichier?: (number | null) | Media;
  /**
   * Date de publication ou de référence du document.
   */
  date?: string | null;
  description_courte?: string | null;
  /**
   * Document annoncé mais pas encore publié.
   */
  a_paraitre?: boolean | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'actualites';
        value: number | Actualite;
      } | null)
    | ({
        relationTo: 'evenements';
        value: number | Evenement;
      } | null)
    | ({
        relationTo: 'equipe';
        value: number | Equipe;
      } | null)
    | ({
        relationTo: 'temoignages';
        value: number | Temoignage;
      } | null)
    | ({
        relationTo: 'partenaires';
        value: number | Partenaire;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  noindex?: T;
  hero?:
    | T
    | {
        enabled?: T;
        titre?: T;
        sousTitre?: T;
        accroche?: T;
        variant?: T;
        cta_primaire?:
          | T
          | {
              label?: T;
              href?: T;
              externe?: T;
            };
        cta_secondaire?:
          | T
          | {
              label?: T;
              href?: T;
              externe?: T;
            };
      };
  sections?:
    | T
    | {
        prose?:
          | T
          | {
              titre?: T;
              fond?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              fond?: T;
              ton?: T;
              titre?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        lettre?:
          | T
          | {
              titre?: T;
              fond?: T;
              ouverture?: T;
              corps?: T;
              signature?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        citation?:
          | T
          | {
              fond?: T;
              citation?: T;
              auteur?: T;
              role?: T;
              variant?: T;
              fictif?: T;
              id?: T;
              blockName?: T;
            };
        'citation-large'?:
          | T
          | {
              fond?: T;
              citation?: T;
              auteur?: T;
              role?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        'stat-majeste'?:
          | T
          | {
              titre?: T;
              fond?: T;
              chiffre?: T;
              texte?: T;
              source?: T;
              eyebrow?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        'chiffre-detail'?:
          | T
          | {
              titre?: T;
              fond?: T;
              chiffre?: T;
              texte?: T;
              source?: T;
              alignement?: T;
              couleur?: T;
              id?: T;
              blockName?: T;
            };
        cartes?:
          | T
          | {
              titre?: T;
              fond?: T;
              colonnes?: T;
              cartes?:
                | T
                | {
                    titre?: T;
                    description?: T;
                    href?: T;
                    cta?: T;
                    couleur?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        valeurs?:
          | T
          | {
              titre?: T;
              fond?: T;
              valeurs?:
                | T
                | {
                    nom?: T;
                    description?: T;
                    couleur?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formats?:
          | T
          | {
              titre?: T;
              fond?: T;
              colonnes?: T;
              formats?:
                | T
                | {
                    titre?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          point?: T;
                          id?: T;
                        };
                    couleur?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          externe?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        etapes?:
          | T
          | {
              titre?: T;
              fond?: T;
              couleur?: T;
              etapes?:
                | T
                | {
                    titre?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              titre?: T;
              fond?: T;
              questions?:
                | T
                | {
                    question?: T;
                    reponse?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              titre?: T;
              fond?: T;
              intro?: T;
              stats?:
                | T
                | {
                    valeur?: T;
                    legende?: T;
                    source?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'deux-colonnes'?:
          | T
          | {
              titre?: T;
              fond?: T;
              inverse?: T;
              texte?: T;
              picto_couleur?: T;
              image?: T;
              image_alt?: T;
              id?: T;
              blockName?: T;
            };
        'texte-photo'?:
          | T
          | {
              titre?: T;
              fond?: T;
              texte?: T;
              image?: T;
              image_alt?: T;
              image_legende?: T;
              image_credit?: T;
              position?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        figure?:
          | T
          | {
              fond?: T;
              image?: T;
              alt?: T;
              legende?: T;
              credit?: T;
              taille?: T;
              id?: T;
              blockName?: T;
            };
        galerie?:
          | T
          | {
              titre?: T;
              fond?: T;
              colonnes?: T;
              lightbox?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    legende?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bandeau-image'?:
          | T
          | {
              image?: T;
              alt?: T;
              titre?: T;
              sousTitre?: T;
              hauteur?: T;
              position_texte?: T;
              position_verticale?: T;
              scrim?: T;
              id?: T;
              blockName?: T;
            };
        portraits?:
          | T
          | {
              titre?: T;
              fond?: T;
              colonnes?: T;
              forme?: T;
              personnes?:
                | T
                | {
                    nom?: T;
                    role?: T;
                    photo?: T;
                    photo_alt?: T;
                    bio?: T;
                    lien?: T;
                    lien_label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              titre?: T;
              fond?: T;
              alignement?: T;
              etapes?:
                | T
                | {
                    date?: T;
                    titre?: T;
                    texte?: T;
                    image?: T;
                    image_alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        temoignages?:
          | T
          | {
              titre?: T;
              fond?: T;
              contexte?: T;
              limite?: T;
              ids?:
                | T
                | {
                    slug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        equipe?:
          | T
          | {
              titre?: T;
              fond?: T;
              intro?: T;
              forme?: T;
              colonnes?: T;
              ids?:
                | T
                | {
                    slug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              fond?: T;
              titre?: T;
              corps?: T;
              cta_primaire?:
                | T
                | {
                    label?: T;
                    href?: T;
                    externe?: T;
                  };
              cta_secondaire?:
                | T
                | {
                    label?: T;
                    href?: T;
                    externe?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  date?: T;
  auteur?: T;
  cover?: T;
  cover_alt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements_select".
 */
export interface EvenementsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date_debut?: T;
  date_fin?: T;
  lieu?: T;
  adresse?: T;
  cover?: T;
  public?: T;
  gratuit?: T;
  inscription_url?: T;
  body?: T;
  fictif?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe_select".
 */
export interface EquipeSelect<T extends boolean = true> {
  slug?: T;
  nom?: T;
  role?: T;
  photo?: T;
  bio_courte?: T;
  linkedin?: T;
  ordre?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages_select".
 */
export interface TemoignagesSelect<T extends boolean = true> {
  slug?: T;
  auteur?: T;
  role?: T;
  contexte?: T;
  photo?: T;
  citation?: T;
  ordre?: T;
  a_la_une?: T;
  fictif?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires_select".
 */
export interface PartenairesSelect<T extends boolean = true> {
  slug?: T;
  nom?: T;
  type?: T;
  logo?: T;
  url?: T;
  description_courte?: T;
  ordre?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  slug?: T;
  titre?: T;
  categorie?: T;
  fichier?: T;
  date?: T;
  description_courte?: T;
  a_paraitre?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité, mission, contact, réseaux, liens HelloAsso. Pas de credentials ici (SMTP, etc.) — ceux-là sont dans Infisical.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  nom_asso: string;
  url: string;
  accroche_globale: string;
  mission: string;
  directeur_publication: string;
  siren?: string | null;
  rna?: string | null;
  adresse?: string | null;
  reseaux?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  /**
   * URLs publiques des campagnes HelloAsso. Visibles dans les boutons "Faire un don", "Adhérer", "Newsletter".
   */
  helloasso?: {
    don?: string | null;
    adhesion?: string | null;
    newsletter?: string | null;
  };
  banderole_urgence?: {
    /**
     * Active la banderole sur toutes les pages.
     */
    active?: boolean | null;
    /**
     * Markdown inline supporté (**gras**, *italique*, [lien](url)).
     */
    message?: string | null;
    couleur?: ('orange' | 'violet' | 'magenta') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  nom_asso?: T;
  url?: T;
  accroche_globale?: T;
  mission?: T;
  directeur_publication?: T;
  siren?: T;
  rna?: T;
  adresse?: T;
  reseaux?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  helloasso?:
    | T
    | {
        don?: T;
        adhesion?: T;
        newsletter?: T;
      };
  banderole_urgence?:
    | T
    | {
        active?: T;
        message?: T;
        couleur?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}